### ISSUE TITLE
bug when launching tool

### ISSUE THREAD

**Issue by gibbles2244** [imchillin/CMTool#65]
I receive this error message when I try to launch the tool.

Concept Matirx ran into an error.

Please submit a bug report with the following information.
 
======================================================
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> Lumina.Excel.Exceptions.ExcelSheetColumnChecksumMismatchException: sheet race column hash mismatch! expected hash: 1019666222, actual hash: 872644730!
   at Lumina.Excel.ExcelModule.GetSheet[T](String name, Language language, Nullable`1 expectedHash)
   at Lumina.Excel.ExcelModule.GetSheet[T](Language language)
   at ConceptMatrix.ViewModel.MainViewModel.<>c.<Initialize>b__37_0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Lumina.Excel.Exceptions.ExcelSheetColumnChecksumMismatchException: sheet race column hash mismatch! expected hash: 1019666222, actual hash: 872644730!
   at Lumina.Excel.ExcelModule.GetSheet[T](String name, Language language, Nullable`1 expectedHash)
   at Lumina.Excel.ExcelModule.GetSheet[T](Language language)
   at ConceptMatrix.ViewModel.MainViewModel.<>c.<Initialize>b__37_0()
   at System.Threading.Tasks.Task.Execute()<---

======================================================

I also see this one when i select yes on the first one

Concept Matirx ran into an error.

Please submit a bug report with the following information.
 
======================================================
System.Threading.ThreadStateException: Current thread must be set to single thread apartment (STA) mode before OLE calls can be made.
   at System.Windows.OleServicesContext.SetDispatcherThread()
   at System.Windows.OleServicesContext.get_CurrentOleServicesContext()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at ConceptMatrix.App.TaskSchedulerOnUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs e)
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
======================================================

It recommends I submit a bug report so I hope this helps

**Comment by Bluefissure** [comment]
Please download [2.0.9.21](https://github.com/imchillin/CMTool/releases/tag/2.0.9.21).
